en:
  hold: "Hold"
  pending: "Pending"
  open: "Open"
  solved: "Solved"
  closed: "Closed"
  do_on_closed_ticket: "Create a new ticket using the *Support* command"
  on_this_thread_already_closed: "already closed for this thread"
  ticket: "Ticket"
  about_hold: "This means that the solution to the issue is transferred to a third party and does not depend on technical support: to another department or a third party.\nOnce the necessary information is received, the decision will continue or be completed"
  about_pending: "The appeal has been resolved, but if you still have questions about the same appeal - write your message to this thread, the ticket will be back in operation"
  about_open: "The appeal has been transferred to a specialist for processing"
  about_closed: "The appeal is resolved and the ticket is closed *finally*. If you need to continue, then create a new case using the *Support* command"
  now_in_status: "now in status"
  user: "User"
  message: "Message"
  bot: "Bot"
ru:
  hold: "Удержание"
  pending: "Ожидание"
  open: "Открыт"
  solved: "Выполнено"
  closed: "Закрыт"
  do_on_closed_ticket: "Создай новое обращение используя команду *Support*"
  on_this_thread_already_closed: "по этому треду уже закрыт"
  ticket: "Тикет"
  about_hold: "Это означает, что решение вопроса передано третьей стороне и от техподдержки не зависит: в другой отдел или другому ответственному лицу.\nКак только будет получена необходимая информация, решение продолжится или будет завершено"
  about_pending: "Обращение решено, но если есть еще вопросы по этому же обращению - напиши свое сообщение в этот тред, тикет снова попадет в работу"
  about_open: "Обращение передано в обработку специалисту"
  about_closed: "Обращение решено и тикет закрыт *окончательно*. Если требуется продолжение, то создай новое обращение используя команду *Support*"
  now_in_status: "теперь в статусе"
  user: "Пользователь"
  message: "Сообщение"
  bot: "Бот"